network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s31f6:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.1.220/24
      gateway4: 192.168.1.254
      nameservers:
        addresses:
          - 192.168.1.254
